services:
  springboot-app:
    build:
      context: ./chap01_01_bootProject
      dockerfile: Dockerfile
    image: raccoonohgiraffer/boot_compose_project
    container_name : boot_container
    ports:
      - "8055:7777"
  react-app:
    build:
      context: ./chap01_02_reactProject
      dockerfile: Dockerfile
    image: raccoonohgiraffer/react_compose_project
    container_name : react_container
    ports:
      - "8011:5173"
