apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot001dep
spec:
  selector:
    matchLabels:
      app: boot001kube
  replicas: 3
  template:
    metadata:
      labels:
        app: boot001kube
    spec:
      containers:
      - name: boot-container
        image: raccoonohgiraffer/goorm_b_proj:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7777