CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(50) NOT NULL UNIQUE,
                       password VARCHAR(100) NOT NULL,
                       role VARCHAR(20)
);

INSERT INTO users (username, password, role)
VALUES ('testuser', '$2a$10$Q8U6tkF.buA8VCEd3qz4fO5s/5cAyUvYKmZcbngEvUwLIP/dRLioS', 'USER');

INSERT INTO users (username, password, role)
VALUES (
           'testuser',
           '$2a$10$Q8U6tkF.buA8VCEd3qz4fO5s/5cAyUvYKmZcbngEvUwLIP/dRLioS', -- "1234" 암호화
           'USER'
       );